### ISSUE TITLE
As a user, I would like to be able to pin important sources to the top of the list

### ISSUE THREAD

**Issue by ToonDragon** [CS2103-AY1819S2-W13-3/main#149]
so that I can see at a glance my important sources.

**Comment by case141** [comment]
Regarding deleting a pinned source, you can remove the pinned source from the text file by decreasing its count which would be more intuitive compared to not allowing users to delete a pinned source. You can add the method for this function in the model class so that I can use it in my delete command.

**Comment by ToonDragon** [comment]
Tests and updates to developer guide and user guide still pending.

Issue will remain open for now.
