### ISSUE TITLE
[Outdated/Unused] Planned enhancements to the source model

### ISSUE THREAD

**Issue by ToonDragon** [CS2103-AY1819S2-W13-3/main#68]
- Add additional functions to aid usage
- Add checkers to regulate user input and prevent out-of-bounds issues

*The code in this issue has been removed during the major migration of the project in PR#106.

**Comment by case141** [comment]
Darren read your telegram? 
anyways i already reassigned the similar issue to milestone 1.2 titled 'Implement New Model' so i don't think we need the same issue. Regarding why its still titled 'New Model', we should redo the model to use abstraction similar to how the ab4 model is constructed instead of the current sourcemodel that you added. Actually we should hold another meeting to discuss about the major changes that we need to make including the model so that we all agree on what will be done before we actually do anything to the code.

**Comment by ToonDragon** [comment]
Oh i didn't see this comment earlier

My rationale for creating a new issue is that I will be improving the model anyways, so it would not be a completely "new" model.  The future improvements are geared towards making the current model closer to AB4.  So ideally, the new model should have a similar architecture but at the same time it would not be exactly the same since AB4 has a lot of unnecessary abstraction which just make it hard to implement new features.
